task: Spot-Velocity-Rough-v0
env_cfg_entry_point: env_cfg_entry_point
num_envs: 64
seed: 1
capture_video: true
video: false
video_length: 200
video_interval: 2000
disable_fabric: false
distributed: false
headless: true
enable_cameras: true
exp_name: play
torch_deterministic: true
device: cuda:0
checkpoint_path: /home/chandramouli/quadruped/wandb/run-20250623_154954-rav784s7/files/checkpoints/ckpt_491520000.pt
num_eval_envs: 10
num_eval_env_steps: 50 