task: CognitiveRL-Nav-v2
env_cfg_entry_point: env_cfg_entry_point
num_envs: 64
seed: 1
capture_video: true
video: false
video_length: 200
video_interval: 2000
disable_fabric: false
distributed: false
headless: true
enable_cameras: true
exp_name: play
torch_deterministic: true
device: cuda:0
checkpoint_path: /home/user/cognitiverl/wandb/offline-run-20250602_194417-pnrq9ikt/files/checkpoints/ckpt_20480.pt
num_eval_envs: 10
num_eval_env_steps: 50 