task: Leatherback-Nav-v2
env_cfg_entry_point: env_cfg_entry_point
num_envs: 64
seed: 1
capture_video: true
video: false
video_length: 200
video_interval: 2000
disable_fabric: false
distributed: false
headless: false
enable_cameras: true
exp_name: ppo_continuous_action
torch_deterministic: true
device: cuda:0
total_timesteps: 10_000_000
learning_rate: 0.0003
num_steps: 64
anneal_lr: true
gamma: 0.99
gae_lambda: 0.95
num_minibatches: 8
update_epochs: 10
norm_adv: false
clip_coef: 0.2
clip_vloss: true
ent_coef: 0.0
vf_coef: 1.0
max_grad_norm: 1.0
target_kl: 0.01
batch_size: 0
minibatch_size: 0
num_iterations: 0
measure_burnin: 3
agent_type: CNNPPOAgent
checkpoint_interval: 1
num_eval_envs: 3
num_eval_env_steps: 200
log: false
log_video: false